import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonIcon } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';

@Component({ selector:'app-delivery-detail', standalone:true, imports:[CommonModule, RouterLink, IonButton, IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonIcon, MobileShellComponent], template:`
<wf-customer-shell title="Delivery WF-77842" subtitle="Completed June 24" backRoute="/deliveries"><main class="screen-body stack"><ion-card class="wf-card soft-card"><ion-card-content class="text-center"><div class="success-orb" style="width:76px;height:76px"><ion-icon name="checkmark-circle-outline" style="font-size:42px"></ion-icon></div><h2>420 gallons delivered</h2><p class="caption">Completed at 11:42 AM by Dave Morgan</p></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-content><div class="detail-row"><span>Location</span><strong>North Yard</strong></div><div class="detail-row"><span>Equipment</span><strong>North Yard Generator</strong></div><div class="detail-row"><span>Fuel product</span><strong>ULSD</strong></div><div class="detail-row"><span>Start meter</span><strong>18,240.7 gal</strong></div><div class="detail-row"><span>End meter</span><strong>18,660.7 gal</strong></div><div class="detail-row"><span>Driver</span><strong>Dave Morgan</strong></div></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-header><ion-card-title>Delivery proof</ion-card-title></ion-card-header><ion-card-content><div class="grid-2"><div class="icon-tile" style="width:100%;height:110px"><ion-icon name="camera-outline"></ion-icon></div><div class="icon-tile" style="width:100%;height:110px"><ion-icon name="camera-outline"></ion-icon></div></div><p class="caption">GPS verified at North Yard · QR code WF-EQ-2102 scanned</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" routerLink="/invoice-detail"><ion-icon name="document-text-outline" slot="start"></ion-icon>View invoice</ion-button><ion-button class="wf-button wf-secondary" expand="block"><ion-icon name="download-outline" slot="start"></ion-icon>Download delivery receipt</ion-button></main></wf-customer-shell>` })
export class DeliveryDetailPage {  }
