import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonIcon, IonInput, IonItem, IonSelect, IonSelectOption, IonTextarea } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';

@Component({ selector:'app-equipment-form', standalone:true, imports:[CommonModule, RouterLink, IonButton, IonCard, IonCardContent, IonIcon, IonInput, IonItem, IonSelect, IonSelectOption, IonTextarea, MobileShellComponent], template:`
<wf-customer-shell title="Add equipment" subtitle="Customer asset" backRoute="/equipment"><main class="screen-body stack"><ion-card class="wf-card form-card"><ion-card-content class="stack"><ion-item><ion-input label="Equipment name" labelPlacement="stacked" placeholder="e.g. Backup Generator Tank"></ion-input></ion-item><ion-item><ion-select label="Equipment type" labelPlacement="stacked"><ion-select-option>Generator tank</ion-select-option><ion-select-option>Storage tank</ion-select-option><ion-select-option>Fleet tank</ion-select-option><ion-select-option>Other</ion-select-option></ion-select></ion-item><ion-item><ion-select label="Fuel product" labelPlacement="stacked"><ion-select-option>Ultra-Low Sulfur Diesel</ion-select-option><ion-select-option>Off-road Diesel</ion-select-option><ion-select-option>Regular Unleaded</ion-select-option></ion-select></ion-item><ion-item><ion-input label="Capacity in gallons" labelPlacement="stacked" type="number"></ion-input></ion-item><ion-item><ion-select label="Location" labelPlacement="stacked"><ion-select-option>Main Warehouse</ion-select-option><ion-select-option>North Yard</ion-select-option></ion-select></ion-item><ion-item><ion-textarea label="Access notes" labelPlacement="stacked" autoGrow="true"></ion-textarea></ion-item></ion-card-content></ion-card><ion-card class="wf-card soft-card"><ion-card-content class="row"><ion-icon name="qr-code-outline" style="font-size:24px"></ion-icon><p class="caption" style="margin:0">A WetFuel QR code can be assigned by your franchise administrator or field representative.</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" routerLink="/equipment">Save equipment</ion-button></main></wf-customer-shell>` })
export class EquipmentFormPage {  }
