import { CommonModule } from '@angular/common';import { Component,inject,signal } from '@angular/core';import { ActivatedRoute,Router,RouterLink } from '@angular/router';import { IonButton,IonCard,IonCardContent,IonCardHeader,IonCardTitle,IonIcon } from '@ionic/angular/standalone';import { CustomerApiService,CustomerEquipment } from '../services/customer-api.service';import { CustomerStateService } from '../services/customer-state.service';import { MobileShellComponent } from '../shared/mobile-shell.component';
import { LoaderComponent } from '../shared/loader.component';
@Component({selector:'app-equipment-detail',standalone:true,imports:[CommonModule,RouterLink,IonButton,IonCard,IonCardContent,IonCardHeader,IonCardTitle,IonIcon,MobileShellComponent,LoaderComponent],template:`
<wf-customer-shell title="Equipment details" [subtitle]="equipment()?.qrCode||'Customer asset'" backRoute="/equipment" [showNav]="true"><main class="screen-body stack">@if(equipment();as item){<ion-card class="wf-card hero-card"><ion-card-content><div class="row-between"><div><span class="pill dark">{{item.statusLabel}}</span><h2>{{item.name}}</h2><p class="caption">{{item.siteName}}</p></div><div class="icon-tile"><ion-icon name="cube-outline"></ion-icon></div></div><div style="height:12px"></div><div class="progress-track orange"><span [style.width.%]="item.estimatedLevelPercent||0"></span></div><p style="margin-bottom:0">Estimated level: {{item.estimatedLevelPercent??'—'}}% · approximately {{estimatedGallons(item)}} gal</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" (click)="order(item)">Order fuel for this equipment</ion-button><ion-card class="wf-card"><ion-card-content><div class="detail-row"><span>Equipment type</span><strong>{{item.type}}</strong></div><div class="detail-row"><span>Fuel product</span><strong>{{item.fuelType}}</strong></div><div class="detail-row"><span>Capacity</span><strong>{{item.capacityGallons||0}} gal</strong></div><div class="detail-row"><span>QR code</span><strong>{{item.qrCode}}</strong></div><div class="detail-row"><span>Serial</span><strong>{{item.serialNumber||'—'}}</strong></div><div class="detail-row"><span>Total delivered</span><strong>{{item.totalGallonsDelivered}} gal</strong></div></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-header><ion-card-title>Recent fuel history</ion-card-title></ion-card-header><ion-card-content>@for(f of item.recentFuelings;track f.id){<div class="detail-row"><span>{{f.completedAt|date:'mediumDate'}} · {{f.jobNumber}}</span><strong>{{f.deliveredGallons}} gal</strong></div>}@empty{<p class="caption">No linked deliveries yet.</p>}</ion-card-content></ion-card><ion-button class="wf-button wf-secondary" [routerLink]="['/equipment-form',item.id]"><ion-icon name="pencil-outline" slot="start"></ion-icon>Edit equipment</ion-button>}@else if(error()){<div class="load-error"><span>{{error()}}</span><button type="button" (click)="load()">Retry</button></div>}@else{<section><wf-loader mode="section" message="Loading equipment..." /></section>}</main></wf-customer-shell>`})
export class EquipmentDetailPage{
  private readonly route=inject(ActivatedRoute);private readonly api=inject(CustomerApiService);private readonly state=inject(CustomerStateService);private readonly router=inject(Router);
  readonly equipment=signal<CustomerEquipment|null>(null);readonly error=signal('');
  ngOnInit():void{this.load();}
  load():void{
    const id=this.route.snapshot.paramMap.get('id');if(!id)return;
    this.error.set('');
    this.api.getEquipmentById(id).subscribe({next:x=>this.equipment.set(x),error:()=>this.error.set('This equipment could not be loaded. Check your connection and try again.')});
  }
  estimatedGallons(x:CustomerEquipment):number{return Math.round((x.capacityGallons??0)*(x.estimatedLevelPercent??0)/100);}
  order(x:CustomerEquipment):void{this.state.selectEquipment(x);void this.router.navigateByUrl('/new-order');}
}
