import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IonButton,IonCard,IonCardContent,IonIcon,IonSearchbar } from '@ionic/angular/standalone';
import { CustomerApiService, CustomerEquipment } from '../services/customer-api.service';
import { MobileShellComponent } from '../shared/mobile-shell.component';
@Component({selector:'app-equipment',standalone:true,imports:[CommonModule,RouterLink,IonButton,IonCard,IonCardContent,IonIcon,IonSearchbar,MobileShellComponent],template:`
<wf-customer-shell title="Equipment" [subtitle]="equipment().length+' registered assets'" [showNav]="true"><main class="screen-body stack"><ion-searchbar placeholder="Search equipment"></ion-searchbar><ion-button class="wf-button" expand="block" routerLink="/equipment-form"><ion-icon slot="start" name="add-outline"></ion-icon>Add equipment</ion-button>
<ion-card *ngFor="let item of equipment()" class="wf-card" [routerLink]="['/equipment-detail',item.id]"><ion-card-content><div class="row"><div class="icon-tile"><ion-icon name="cube-outline"></ion-icon></div><div class="grow"><div class="row-between"><strong>{{item.name}}</strong><span class="pill" [class.warning]="item.status==='needs_service'||(item.estimatedLevelPercent||0)<40" [class.success]="item.status==='active'&&(item.estimatedLevelPercent||0)>=40">{{item.status==='needs_service'?'Service':(item.estimatedLevelPercent||0)+'%'}}</span></div><p class="caption">{{item.qrCode}} · {{item.siteName}}</p><div class="equipment-level"><span [style.width.%]="item.estimatedLevelPercent||0"></span></div><p class="caption" style="margin-bottom:0">{{item.fuelType}} · {{item.capacityGallons||0}} gal</p></div><ion-icon name="chevron-forward-outline"></ion-icon></div></ion-card-content></ion-card>
<ion-card *ngIf="equipment().length===0" class="wf-card"><ion-card-content><p class="caption">No equipment registered. Add an asset before placing an equipment-specific order.</p></ion-card-content></ion-card></main></wf-customer-shell>`})
export class EquipmentPage{private readonly api=inject(CustomerApiService);readonly equipment=signal<CustomerEquipment[]>([]);ionViewWillEnter():void{this.api.getEquipment().subscribe({next:rows=>this.equipment.set(rows)});}}
