import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonicModule } from '@ionic/angular';
import { MobileShellComponent } from '../shared/mobile-shell.component';

@Component({ selector:'app-equipment-detail', standalone:true, imports:[CommonModule, RouterLink, IonicModule, MobileShellComponent], template:`
<wf-customer-shell title="Equipment details" subtitle="EQ-2048" backRoute="/equipment"><main class="screen-body stack"><ion-card class="wf-card hero-card"><ion-card-content><div class="row-between"><div><span class="pill dark">Needs fuel</span><h2>Backup Generator Tank</h2><p style="opacity:.72">Main Warehouse</p></div><div class="icon-tile" style="background:rgba(255,255,255,.14);color:#fff"><ion-icon name="cube-outline"></ion-icon></div></div><div style="height:12px"></div><div class="equipment-level"><span style="width:32%"></span></div><p style="margin-bottom:0">Estimated level: 32% · approximately 320 gal</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" routerLink="/new-order">Order fuel for this equipment</ion-button><ion-card class="wf-card"><ion-card-content><div class="detail-row"><span>Equipment type</span><strong>Generator tank</strong></div><div class="detail-row"><span>Fuel product</span><strong>ULSD</strong></div><div class="detail-row"><span>Capacity</span><strong>1,000 gal</strong></div><div class="detail-row"><span>QR code</span><strong>WF-EQ-2048</strong></div><div class="detail-row"><span>Last delivery</span><strong>May 29 · 500 gal</strong></div></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-header><ion-card-title>Recent fuel history</ion-card-title></ion-card-header><ion-card-content><div class="detail-row"><span>May 29, 2026</span><strong>500 gal</strong></div><div class="detail-row"><span>Apr 15, 2026</span><strong>350 gal</strong></div><div class="detail-row"><span>Mar 4, 2026</span><strong>480 gal</strong></div></ion-card-content></ion-card><div class="grid-2"><ion-button class="wf-button wf-secondary" routerLink="/equipment-form"><ion-icon name="pencil-outline" slot="start"></ion-icon>Edit</ion-button><ion-button class="wf-button wf-secondary"><ion-icon name="qr-code-outline" slot="start"></ion-icon>QR code</ion-button></div></main></wf-customer-shell>` })
export class EquipmentDetailPage {  }
