import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonIcon } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';
import { ORDERS } from '../data/mock-data';
import { CustomerStateService } from '../services/customer-state.service';
@Component({ selector:'app-home', standalone:true, imports:[CommonModule, RouterLink, IonButton, IonCard, IonCardContent, IonIcon, MobileShellComponent], template:`
<wf-customer-shell [title]="'Good morning, ' + (state.profile()?.contactFirstName || 'there')" [subtitle]="state.profile()?.companyName || 'Customer account'" [showNav]="true"><main class="screen-body stack">
<ion-card class="wf-card hero-card"><ion-card-content><div class="row-between"><div><span class="pill dark">Driver en route</span><h2 style="margin:16px 0 5px">Your delivery is 24 min away</h2><p style="margin:0;opacity:.75">Order WF-78312 · Main Warehouse</p></div><div class="icon-tile" style="background:rgba(255,255,255,.14);color:#fff"><ion-icon name="truck-outline"></ion-icon></div></div><div style="height:16px"></div><ion-button class="wf-button" color="tertiary" expand="block" routerLink="/live-tracking">Track live delivery</ion-button></ion-card-content></ion-card>
<ion-button class="wf-button" expand="block" routerLink="/new-order"><ion-icon slot="start" name="add-outline"></ion-icon>Order fuel</ion-button>
<section class="grid-3"><ion-card class="wf-card"><ion-card-content class="metric"><span class="label">Active orders</span><strong>2</strong><span class="caption">View status</span></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-content class="metric"><span class="label">Equipment</span><strong>3</strong><span class="caption">1 needs fuel</span></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-content class="metric"><span class="label">Open invoices</span><strong>$1.6k</strong><span class="caption">Net 30</span></ion-card-content></ion-card></section>
<section><div class="row-between"><h2 class="section-title">Equipment attention</h2><a routerLink="/equipment" class="caption">View all</a></div><ion-card class="wf-card warning-card"><ion-card-content><div class="row"><div class="icon-tile"><ion-icon name="cube-outline"></ion-icon></div><div class="grow"><strong>Backup Generator Tank</strong><p class="caption" style="margin:5px 0 9px">Main Warehouse · estimated 32% remaining</p><div class="equipment-level"><span style="width:32%"></span></div></div><ion-icon name="chevron-forward-outline"></ion-icon></div></ion-card-content></ion-card></section>
<section><h2 class="section-title">Quick access</h2><div class="grid-2"><ion-card class="wf-card" routerLink="/invoices"><ion-card-content class="row"><div class="icon-tile"><ion-icon name="document-text-outline"></ion-icon></div><strong>Invoices</strong></ion-card-content></ion-card><ion-card class="wf-card" routerLink="/deliveries"><ion-card-content class="row"><div class="icon-tile"><ion-icon name="receipt-outline"></ion-icon></div><strong>Delivery history</strong></ion-card-content></ion-card><ion-card class="wf-card" routerLink="/locations"><ion-card-content class="row"><div class="icon-tile"><ion-icon name="location-outline"></ion-icon></div><strong>Locations</strong></ion-card-content></ion-card><ion-card class="wf-card" routerLink="/support"><ion-card-content class="row"><div class="icon-tile"><ion-icon name="help-circle-outline"></ion-icon></div><strong>Get support</strong></ion-card-content></ion-card></div></section>
</main></wf-customer-shell>` })
export class HomePage { readonly activeOrder=ORDERS[0]; readonly state=inject(CustomerStateService); }
