import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonicModule } from '@ionic/angular';
import { MobileShellComponent } from '../shared/mobile-shell.component';
import { CustomerStateService } from '../services/customer-state.service';
@Component({ selector:'app-new-order', standalone:true, imports:[CommonModule, RouterLink, IonicModule, MobileShellComponent], template:`
<wf-customer-shell title="Order fuel" subtitle="Step 1 of 4" backRoute="/home"><main class="screen-body stack"><p class="page-lead">Choose where the fuel should be delivered and which equipment should receive it.</p><ion-card class="wf-card selection-card" routerLink="/select-location"><ion-card-content><div class="row"><div class="icon-tile"><ion-icon name="location-outline"></ion-icon></div><div class="grow"><span class="caption">Delivery location</span><h3 style="margin:4px 0">{{state.selectedLocation().name}}</h3><p class="caption" style="margin:0">{{state.selectedLocation().address}}</p></div><ion-icon name="chevron-forward-outline"></ion-icon></div></ion-card-content></ion-card><ion-card class="wf-card selection-card" routerLink="/select-equipment"><ion-card-content><div class="row"><div class="icon-tile"><ion-icon name="cube-outline"></ion-icon></div><div class="grow"><span class="caption">Equipment</span><h3 style="margin:4px 0">{{state.selectedEquipment().name}}</h3><p class="caption" style="margin:0">{{state.selectedEquipment().fuel}} · {{state.selectedEquipment().current}}% remaining</p></div><ion-icon name="chevron-forward-outline"></ion-icon></div></ion-card-content></ion-card><ion-card class="wf-card soft-card"><ion-card-content class="row"><ion-icon name="information-circle-outline" style="font-size:24px"></ion-icon><p class="caption" style="margin:0">Pricing is calculated using your customer agreement, daily fuel rates and applicable taxes.</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" routerLink="/order-details">Continue to fuel details</ion-button></main></wf-customer-shell>` })
export class NewOrderPage { constructor(readonly state:CustomerStateService){} }
