import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonIcon } from '@ionic/angular/standalone';
import { firstValueFrom } from 'rxjs';
import { CustomerApiService } from '../services/customer-api.service';
import { CustomerStateService } from '../services/customer-state.service';
import { MobileShellComponent } from '../shared/mobile-shell.component';
@Component({ selector:'app-new-order', standalone:true, imports:[CommonModule,RouterLink,IonButton,IonCard,IonCardContent,IonIcon,MobileShellComponent], template:`
<wf-customer-shell title="Order fuel" subtitle="Step 1 of 4" backRoute="/home"><main class="screen-body stack"><p class="page-lead">Choose where the fuel should be delivered and which equipment should receive it.</p><ion-card class="wf-card selection-card" routerLink="/select-location"><ion-card-content><div class="row"><div class="icon-tile"><ion-icon name="location-outline"></ion-icon></div><div class="grow"><span class="caption">Delivery location</span><h3 style="margin:4px 0">{{state.selectedLocation()?.name || 'Select a location'}}</h3><p class="caption" style="margin:0">{{state.selectedLocation()?.address || 'Required'}}</p></div><ion-icon name="chevron-forward-outline"></ion-icon></div></ion-card-content></ion-card><ion-card class="wf-card selection-card" routerLink="/select-equipment"><ion-card-content><div class="row"><div class="icon-tile"><ion-icon name="cube-outline"></ion-icon></div><div class="grow"><span class="caption">Equipment</span><h3 style="margin:4px 0">{{state.selectedEquipment()?.name || 'Select equipment'}}</h3><p class="caption" style="margin:0">@if(state.selectedEquipment();as equipment){ {{equipment.fuel}} · {{equipment.current}}% remaining }@else{ Required }</p></div><ion-icon name="chevron-forward-outline"></ion-icon></div></ion-card-content></ion-card><ion-card class="wf-card soft-card"><ion-card-content class="row"><ion-icon name="information-circle-outline" style="font-size:24px"></ion-icon><p class="caption" style="margin:0">Pricing is calculated using your customer agreement, daily fuel rates and applicable taxes.</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" [disabled]="!state.canAccessOrderStep('details')" routerLink="/order-details">Continue to fuel details</ion-button></main></wf-customer-shell>` })
export class NewOrderPage {
  private readonly api=inject(CustomerApiService);
  readonly state=inject(CustomerStateService);
  ionViewWillEnter():void{void this.loadDefaults();}
  private async loadDefaults():Promise<void>{const [sites,equipment]=await Promise.all([firstValueFrom(this.api.getSites()),firstValueFrom(this.api.getEquipment())]);if(this.state.selectedLocation()||this.state.selectedEquipment())this.state.reconcileDraft(sites,equipment);if(!this.state.selectedLocation()){const site=sites.find(x=>x.isDefault)??sites[0];if(site)this.state.selectLocation(site);}if(!this.state.selectedEquipment()){const siteId=this.state.selectedLocation()?.id;const item=equipment.find(x=>x.isActive&&x.siteId===siteId)??equipment.find(x=>x.isActive);if(item)this.state.selectEquipment(item);}}
}
