import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonInput, IonItem, IonLabel, IonRange, IonSelect, IonSelectOption } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';
import { CustomerStateService } from '../services/customer-state.service';
@Component({ selector:'app-order-details', standalone:true, imports:[CommonModule, FormsModule, RouterLink, IonButton, IonCard, IonCardContent, IonInput, IonItem, IonLabel, IonRange, IonSelect, IonSelectOption, MobileShellComponent], template:`
<wf-customer-shell title="Fuel details" subtitle="Step 2 of 4" backRoute="/new-order"><main class="screen-body stack"><ion-card class="wf-card form-card"><ion-card-content class="stack"><ion-item><ion-select label="Fuel type" labelPlacement="stacked" [(ngModel)]="fuel"><ion-select-option>Ultra-Low Sulfur Diesel</ion-select-option><ion-select-option>Off-road Diesel</ion-select-option><ion-select-option>Regular Unleaded</ion-select-option></ion-select></ion-item><ion-item><ion-input label="Requested gallons" labelPlacement="stacked" type="number" [(ngModel)]="gallons"></ion-input></ion-item><ion-range min="100" max="1000" step="25" snaps="true" pin="true" [(ngModel)]="gallons"><ion-label slot="start">100</ion-label><ion-label slot="end">1,000 gal</ion-label></ion-range><ion-item><ion-select label="Fill preference" labelPlacement="stacked" value="requested"><ion-select-option value="requested">Deliver requested quantity</ion-select-option><ion-select-option value="fill">Fill equipment safely</ion-select-option></ion-select></ion-item></ion-card-content></ion-card><ion-card class="wf-card soft-card"><ion-card-content><div class="detail-row"><span>Estimated fuel subtotal</span><strong>{{gallons * 3.42 | currency}}</strong></div><div class="detail-row"><span>Estimated taxes & fees</span><strong>{{gallons * .18 | currency}}</strong></div><div class="detail-row"><span>Estimated total</span><strong>{{gallons * 3.60 | currency}}</strong></div><p class="caption">Final price is based on actual delivered volume and the rate effective at delivery.</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" routerLink="/schedule-delivery" (click)="save()">Continue to scheduling</ion-button></main></wf-customer-shell>` })
export class OrderDetailsPage { fuel=this.state.fuelType(); gallons=this.state.gallons(); constructor(readonly state:CustomerStateService){} save(){this.state.fuelType.set(this.fuel);this.state.gallons.set(Number(this.gallons));} }
