import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonIcon } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';

@Component({ selector:'app-order-status', standalone:true, imports:[CommonModule, RouterLink, IonButton, IonCard, IonCardContent, IonIcon, MobileShellComponent], template:`
<wf-customer-shell title="Order WF-78312" subtitle="Driver en route" backRoute="/orders"><main class="screen-body stack"><ion-card class="wf-card hero-card"><ion-card-content><div class="row-between"><div><span class="pill dark">Estimated arrival</span><h2 style="font-size:34px;margin:14px 0 4px">24 minutes</h2><p style="margin:0;opacity:.75">10:48 AM estimated arrival</p></div><div class="icon-tile" style="background:rgba(255,255,255,.14);color:#fff"><ion-icon name="truck-outline"></ion-icon></div></div><ion-button class="wf-button" color="tertiary" expand="block" routerLink="/live-tracking" style="margin-top:16px">Open live tracking</ion-button></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-content><div class="timeline"><div class="timeline-item"><strong>Order confirmed</strong><p class="caption">July 2 · 4:18 PM</p></div><div class="timeline-item"><strong>Driver assigned</strong><p class="caption">Dave Morgan · Truck WF-27</p></div><div class="timeline-item"><strong>Driver en route</strong><p class="caption">Left depot at 10:02 AM</p></div><div class="timeline-item pending"><strong>Delivery in progress</strong><p class="caption">Waiting for arrival</p></div><div class="timeline-item pending"><strong>Delivery complete</strong></div></div></ion-card-content></ion-card><ion-card class="wf-card"><ion-card-content><div class="detail-row"><span>Location</span><strong>Main Warehouse</strong></div><div class="detail-row"><span>Equipment</span><strong>Backup Generator Tank</strong></div><div class="detail-row"><span>Requested</span><strong>500 gal ULSD</strong></div><div class="detail-row"><span>Driver</span><strong>Dave Morgan</strong></div></ion-card-content></ion-card><div class="grid-2"><ion-button class="wf-button wf-secondary" expand="block"><ion-icon slot="start" name="call-outline"></ion-icon>Call dispatch</ion-button><ion-button class="wf-button wf-secondary" expand="block"><ion-icon slot="start" name="chatbubble-outline"></ion-icon>Message</ion-button></div></main></wf-customer-shell>` })
export class OrderStatusPage {  }
