import {CommonModule} from '@angular/common';
import {Component,inject} from '@angular/core';
import {Router,RouterLink} from '@angular/router';
import {IonButton,IonCard,IonCardContent,IonCardHeader,IonCardSubtitle,IonCardTitle,IonCheckbox} from '@ionic/angular/standalone';
import {MobileShellComponent} from '../shared/mobile-shell.component';
import {CustomerStateService} from '../services/customer-state.service';
import {ToastService} from '../services/toast.service';
@Component({selector:'app-order-review',standalone:true,imports:[CommonModule,RouterLink,IonButton,IonCard,IonCardContent,IonCardHeader,IonCardSubtitle,IonCardTitle,IonCheckbox,MobileShellComponent],template:`
<wf-customer-shell title="Review order" subtitle="Step 4 of 4" backRoute="/schedule-delivery"><main class="screen-body stack">
<ion-card class="wf-card"><ion-card-header><ion-card-subtitle>DELIVERY TO</ion-card-subtitle><ion-card-title>{{state.selectedLocation()?.name}}</ion-card-title></ion-card-header><ion-card-content><p class="caption">{{state.selectedLocation()?.address}}</p><div class="detail-row"><span>Equipment</span><strong>{{state.selectedEquipment()?.name}}</strong></div><div class="detail-row"><span>Fuel</span><strong>{{state.fuelType()}}</strong></div><div class="detail-row"><span>Requested volume</span><strong>{{state.gallons()}} gal</strong></div><div class="detail-row"><span>Date</span><strong>{{state.deliveryDate()}}</strong></div><div class="detail-row"><span>Window</span><strong>{{state.deliveryWindow()}}</strong></div></ion-card-content></ion-card>
<ion-card class="wf-card soft-card"><ion-card-content>@if(state.estimate();as estimate){<div class="detail-row"><span>Estimated subtotal</span><strong>{{estimate.estimatedSubtotal|currency}}</strong></div><div class="detail-row"><span>Estimated taxes & fees</span><strong>{{estimate.estimatedTaxesFees|currency}}</strong></div><div class="detail-row"><span>Estimated order total</span><strong>{{estimate.estimatedTotal|currency}}</strong></div>}@else if(state.estimateLoading()){<p class="caption" style="margin:0">Refreshing current price and taxes...</p>}@else{<p class="caption" style="margin:0">{{state.estimateError()||'Pricing estimate is unavailable.'}}</p>}<p class="caption">Billing terms: Net 30. Final invoice is created after delivery.</p></ion-card-content></ion-card>
<ion-checkbox [checked]="confirmed" (ionChange)="confirmed=$event.detail.checked" labelPlacement="end">I confirm the site and equipment information is correct.</ion-checkbox><ion-button class="wf-button" expand="block" [disabled]="!confirmed||submitting||state.estimateLoading()||!state.estimate()" (click)="placeOrder()">{{submitting?'Placing order...':'Place fuel order'}}</ion-button><ion-button class="wf-button wf-secondary" expand="block" routerLink="/new-order">Edit order</ion-button>
</main></wf-customer-shell>`})
export class OrderReviewPage{confirmed=true;submitting=false;private readonly toast=inject(ToastService);constructor(readonly state:CustomerStateService,private readonly router:Router){}async ionViewWillEnter():Promise<void>{try{await this.state.refreshEstimate();}catch(e:any){void this.toast.error(e?.error?.message??e?.error?.title??e?.message??'Pricing estimate is unavailable.');}}async placeOrder():Promise<void>{if(this.submitting)return;this.submitting=true;try{const estimate=await this.state.refreshEstimate();if(!estimate)throw new Error('Pricing estimate is unavailable.');const order=await this.state.submitOrder();await this.router.navigate(['/order-confirmation',order.id],{replaceUrl:true});}catch(e:any){void this.toast.error(e?.error?.message??e?.error?.title??e?.message??'The order could not be submitted.');}finally{this.submitting=false;}}}
