import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonCardHeader, IonCardSubtitle, IonCardTitle, IonCheckbox } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';
import { CustomerStateService } from '../services/customer-state.service';
@Component({ selector:'app-order-review', standalone:true, imports:[CommonModule, RouterLink, IonButton, IonCard, IonCardContent, IonCardHeader, IonCardSubtitle, IonCardTitle, IonCheckbox, MobileShellComponent], template:`
<wf-customer-shell title="Review order" subtitle="Step 4 of 4" backRoute="/schedule-delivery"><main class="screen-body stack"><ion-card class="wf-card"><ion-card-header><ion-card-subtitle>DELIVERY TO</ion-card-subtitle><ion-card-title>{{state.selectedLocation().name}}</ion-card-title></ion-card-header><ion-card-content><p class="caption">{{state.selectedLocation().address}}</p><div class="detail-row"><span>Equipment</span><strong>{{state.selectedEquipment().name}}</strong></div><div class="detail-row"><span>Fuel</span><strong>{{state.fuelType()}}</strong></div><div class="detail-row"><span>Requested volume</span><strong>{{state.gallons()}} gal</strong></div><div class="detail-row"><span>Date</span><strong>{{state.deliveryDate()}}</strong></div><div class="detail-row"><span>Window</span><strong>{{state.deliveryWindow()}}</strong></div></ion-card-content></ion-card><ion-card class="wf-card soft-card"><ion-card-content><div class="detail-row"><span>Estimated subtotal</span><strong>{{state.gallons()*3.42 | currency}}</strong></div><div class="detail-row"><span>Estimated taxes & fees</span><strong>{{state.gallons()*.18 | currency}}</strong></div><div class="detail-row"><span>Estimated order total</span><strong>{{state.gallons()*3.60 | currency}}</strong></div><p class="caption">Billing terms: Net 30. Final invoice is created after delivery.</p></ion-card-content></ion-card><ion-checkbox checked="true" labelPlacement="end">I confirm the site and equipment information is correct.</ion-checkbox><ion-button class="wf-button" expand="block" routerLink="/order-confirmation">Place fuel order</ion-button><ion-button class="wf-button wf-secondary" expand="block" routerLink="/new-order">Edit order</ion-button></main></wf-customer-shell>` })
export class OrderReviewPage { constructor(readonly state:CustomerStateService){} }
