import {CommonModule} from '@angular/common';
import {Component,inject,signal} from '@angular/core';
import {ActivatedRoute,Router,RouterLink} from '@angular/router';
import {IonButton,IonCard,IonCardContent,IonIcon} from '@ionic/angular/standalone';
import {MobileShellComponent} from '../shared/mobile-shell.component';
import {LoaderComponent} from '../shared/loader.component';
import {CustomerApiService,CustomerOrder} from '../services/customer-api.service';
@Component({selector:'app-order-confirmation',standalone:true,imports:[CommonModule,RouterLink,IonButton,IonCard,IonCardContent,IonIcon,MobileShellComponent,LoaderComponent],template:`<wf-customer-shell title="Order confirmed" subtitle="WetFuel"><main class="screen-body stack text-center">@if(order();as x){<div class="success-orb"><ion-icon name="checkmark-circle-outline"></ion-icon></div><div><h2>Your fuel order is in</h2><p class="page-lead">Order <strong>{{x.orderNumber}}</strong> has been sent to dispatch for scheduling.</p></div><ion-card class="wf-card"><ion-card-content><div class="detail-row"><span>Delivery date</span><strong>{{x.requestedDate|date:'mediumDate'}}</strong></div><div class="detail-row"><span>Time preference</span><strong>{{x.deliveryWindow}}</strong></div><div class="detail-row"><span>Requested volume</span><strong>{{x.requestedGallons}} gal</strong></div><div class="detail-row"><span>Location</span><strong>{{x.siteName}}</strong></div></ion-card-content></ion-card><ion-button class="wf-button" expand="block" type="button" (click)="viewOrder(x.id)">View order</ion-button><ion-button class="wf-button wf-secondary" expand="block" routerLink="/home">Return home</ion-button>}@else{<section><wf-loader mode="section" message="Loading confirmed order..." /></section>}</main></wf-customer-shell>`})
export class OrderConfirmationPage{private readonly api=inject(CustomerApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);readonly order=signal<CustomerOrder|null>(null);ngOnInit():void{const id=this.route.snapshot.paramMap.get('id');if(id)this.api.getOrder(id).subscribe(x=>this.order.set(x));}viewOrder(id:string):void{void this.router.navigate(['/order-status',id]);}}
