import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonIcon, IonItem, IonLabel, IonList } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';

@Component({ selector:'app-profile', standalone:true, imports:[CommonModule, RouterLink, IonButton, IonCard, IonCardContent, IonIcon, IonItem, IonLabel, IonList, MobileShellComponent], template:`
<wf-customer-shell title="Account" subtitle="Acme Facilities" [showNav]="true"><main class="screen-body stack"><ion-card class="wf-card"><ion-card-content class="row"><div class="avatar">SJ</div><div class="grow"><h2 style="margin:0 0 4px">Sarah Johnson</h2><p class="caption" style="margin:0">Operations Manager · Customer #ACM-1048</p></div><ion-button fill="clear"><ion-icon name="pencil-outline"></ion-icon></ion-button></ion-card-content></ion-card><ion-list inset="true"><ion-item button routerLink="/locations"><ion-icon name="location-outline" slot="start"></ion-icon><ion-label>Delivery locations</ion-label></ion-item><ion-item button routerLink="/invoices"><ion-icon name="document-text-outline" slot="start"></ion-icon><ion-label>Billing and invoices</ion-label></ion-item><ion-item button><ion-icon name="card-outline" slot="start"></ion-icon><ion-label><h3>Billing terms</h3><p>Net 30</p></ion-label></ion-item><ion-item button routerLink="/notifications"><ion-icon name="notifications-outline" slot="start"></ion-icon><ion-label>Notification preferences</ion-label></ion-item><ion-item button><ion-icon name="shield-checkmark-outline" slot="start"></ion-icon><ion-label>Security and password</ion-label></ion-item><ion-item button routerLink="/support"><ion-icon name="help-circle-outline" slot="start"></ion-icon><ion-label>Help and support</ion-label></ion-item></ion-list><ion-card class="wf-card"><ion-card-content><div class="detail-row"><span>Service provider</span><strong>WetFuel Dallas North</strong></div><div class="detail-row"><span>Account status</span><strong>Active</strong></div><div class="detail-row"><span>Pricing model</span><strong>OPIS + contract margin</strong></div></ion-card-content></ion-card><ion-button class="wf-button wf-secondary" expand="block" routerLink="/login"><ion-icon name="log-out-outline" slot="start"></ion-icon>Sign out</ion-button><p class="caption text-center">WetFuel Customer v1.0.0</p></main></wf-customer-shell>` })
export class ProfilePage {  }
