import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonIcon, IonInput, IonItem, IonLabel, IonSegment, IonSegmentButton, IonSelect, IonSelectOption, IonTextarea, IonToggle } from '@ionic/angular/standalone';
import { MobileShellComponent } from '../shared/mobile-shell.component';
import { CustomerStateService } from '../services/customer-state.service';
@Component({ selector:'app-schedule-delivery', standalone:true, imports:[CommonModule, FormsModule, RouterLink, IonButton, IonCard, IonCardContent, IonIcon, IonInput, IonItem, IonLabel, IonSegment, IonSegmentButton, IonSelect, IonSelectOption, IonTextarea, IonToggle, MobileShellComponent], template:`
<wf-customer-shell title="Schedule delivery" subtitle="Step 3 of 4" backRoute="/order-details"><main class="screen-body stack"><ion-card class="wf-card form-card"><ion-card-content class="stack"><ion-segment [(ngModel)]="scheduleType"><ion-segment-button value="scheduled"><ion-label>Schedule</ion-label></ion-segment-button><ion-segment-button value="soon"><ion-label>Next available</ion-label></ion-segment-button></ion-segment><ion-item><ion-input label="Delivery date" labelPlacement="stacked" type="date" [(ngModel)]="date"></ion-input></ion-item><ion-item><ion-select label="Preferred time window" labelPlacement="stacked" [(ngModel)]="window"><ion-select-option>8:00 AM–10:00 AM</ion-select-option><ion-select-option>10:00 AM–12:00 PM</ion-select-option><ion-select-option>12:00 PM–2:00 PM</ion-select-option><ion-select-option>2:00 PM–4:00 PM</ion-select-option></ion-select></ion-item><ion-item><ion-textarea label="Delivery instructions" labelPlacement="stacked" autoGrow="true" [(ngModel)]="instructions"></ion-textarea></ion-item><ion-toggle checked="true">Notify me when the driver is en route</ion-toggle></ion-card-content></ion-card><ion-card class="wf-card warning-card"><ion-card-content class="row"><ion-icon name="calendar-outline" style="font-size:24px"></ion-icon><p class="caption" style="margin:0">The selected window is a preference. Your confirmed ETA will appear after dispatch assigns a driver.</p></ion-card-content></ion-card><ion-button class="wf-button" expand="block" routerLink="/order-review" (click)="save()">Review order</ion-button></main></wf-customer-shell>` })
export class ScheduleDeliveryPage { scheduleType='scheduled'; date=this.state.deliveryDate(); window=this.state.deliveryWindow(); instructions=this.state.instructions(); constructor(readonly state:CustomerStateService){} save(){this.state.deliveryDate.set(this.date);this.state.deliveryWindow.set(this.window);this.state.instructions.set(this.instructions);} }
