import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IonButton, IonCard, IonCardContent, IonIcon, IonSearchbar } from '@ionic/angular/standalone';
import { CustomerApiService, CustomerSite } from '../services/customer-api.service';
import { CustomerStateService } from '../services/customer-state.service';
import { MobileShellComponent } from '../shared/mobile-shell.component';
@Component({selector:'app-select-location',standalone:true,imports:[CommonModule,RouterLink,IonButton,IonCard,IonCardContent,IonIcon,IonSearchbar,MobileShellComponent],template:`
<wf-customer-shell title="Select location" subtitle="Order fuel" backRoute="/new-order"><main class="screen-body stack"><ion-searchbar placeholder="Search locations"></ion-searchbar><ion-card *ngFor="let location of locations()" class="wf-card selection-card" [class.selected]="state.selectedLocation()?.id===location.id" (click)="state.selectLocation(location)"><ion-card-content><div class="row"><div class="icon-tile"><ion-icon name="business-outline"></ion-icon></div><div class="grow"><div class="row wrap"><strong>{{location.name}}</strong><span *ngIf="location.isDefault" class="pill success">Primary</span></div><p class="caption">{{address(location)}}</p><span class="caption">{{location.contactName || 'No site contact'}}</span></div><ion-icon *ngIf="state.selectedLocation()?.id===location.id" name="checkmark-circle-outline" style="font-size:28px;color:var(--wf-teal)"></ion-icon></div></ion-card-content></ion-card><ion-button class="wf-button" expand="block" routerLink="/new-order" [disabled]="!state.selectedLocation()">Use selected location</ion-button><ion-button class="wf-button wf-secondary" expand="block" routerLink="/location-form"><ion-icon name="add-outline" slot="start"></ion-icon>Add a location</ion-button></main></wf-customer-shell>`})
export class SelectLocationPage{private readonly api=inject(CustomerApiService);readonly state=inject(CustomerStateService);readonly locations=signal<CustomerSite[]>([]);ionViewWillEnter():void{this.api.getSites().subscribe({next:sites=>this.locations.set(sites)});}address(site:CustomerSite):string{return `${site.address}, ${site.city}, ${site.state} ${site.zipCode}`;}}
