import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonicModule } from '@ionic/angular';
import { MobileShellComponent } from '../shared/mobile-shell.component';

@Component({ selector:'app-support', standalone:true, imports:[CommonModule, IonicModule, MobileShellComponent], template:`
<wf-customer-shell title="Help & support" subtitle="We are here to help" backRoute="/profile"><main class="screen-body stack"><ion-card class="wf-card hero-card"><ion-card-content><h2>WetFuel Dallas North</h2><p style="opacity:.75">Dispatch and customer support are available Monday–Friday, 6:00 AM–7:00 PM.</p><div class="grid-2"><ion-button class="wf-button" color="tertiary"><ion-icon slot="start" name="call-outline"></ion-icon>Call</ion-button><ion-button class="wf-button" color="light"><ion-icon slot="start" name="chatbubble-outline"></ion-icon>Message</ion-button></div></ion-card-content></ion-card><ion-list inset="true"><ion-item button><ion-label><h2>Where is my delivery?</h2><p>Tracking, ETA and delayed order guidance</p></ion-label></ion-item><ion-item button><ion-label><h2>Change or cancel an order</h2><p>Contact dispatch before loading begins</p></ion-label></ion-item><ion-item button><ion-label><h2>Invoice or billing question</h2><p>Get help with charges, taxes and payment records</p></ion-label></ion-item><ion-item button><ion-label><h2>Equipment or QR-code issue</h2><p>Update asset information or request a replacement</p></ion-label></ion-item><ion-item button><ion-label><h2>Report a delivery concern</h2><p>Fuel quality, quantity, safety or service issue</p></ion-label></ion-item></ion-list><ion-card class="wf-card"><ion-card-content><div class="detail-row"><span>Dispatch phone</span><strong>(214) 555-0198</strong></div><div class="detail-row"><span>Billing email</span><strong>billing@wetfuel.example</strong></div><div class="detail-row"><span>Emergency</span><strong>Call 911, then dispatch</strong></div></ion-card-content></ion-card></main></wf-customer-shell>` })
export class SupportPage {  }
